name: Hello World

on:
  push:

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: My first step in GH Action
        run: echo "Hello action on ${{ github.event_name }}"

      - name: Second step GH Action by ${{ github.actor }}
        run: echo "Hello action in ${{ github.repository }} ref - ${{ github.ref}}"

      - name: This GH Action running on ${{ runner.os }}
        run: echo "Action job status ${{ job.status }}"
